version: '3.9'
services:
  app:
    container_name: main_app
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql
    networks:
      - fullstack

  mysql:
    image: mysql
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - fullstack

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
